//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnsonControls.BuildingSecurity.XmlRpc3.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class P2000Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal P2000Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JohnsonControls.BuildingSecurity.XmlRpc3.Globalization.P2000Enum", typeof(P2000Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string ALARM_STATE_1 {
            get {
                return ResourceManager.GetString("ALARM_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responding.
        /// </summary>
        public static string ALARM_STATE_2 {
            get {
                return ResourceManager.GetString("ALARM_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string ALARM_STATE_3 {
            get {
                return ResourceManager.GetString("ALARM_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string ALARM_STATE_4 {
            get {
                return ResourceManager.GetString("ALARM_STATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BOOLEAN_TYPE_0 {
            get {
                return ResourceManager.GetString("BOOLEAN_TYPE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BOOLEAN_TYPE_1 {
            get {
                return ResourceManager.GetString("BOOLEAN_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string CONDITION_STATE_0 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string CONDITION_STATE_1 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CONDITION_STATE_11 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypassed.
        /// </summary>
        public static string CONDITION_STATE_16 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string CONDITION_STATE_2 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string CONDITION_STATE_22 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string CONDITION_STATE_23 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string CONDITION_STATE_24 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string CONDITION_STATE_25 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misconfigured.
        /// </summary>
        public static string CONDITION_STATE_26 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string CONDITION_STATE_27 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string CONDITION_STATE_28 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CONDITION_STATE_3 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed.
        /// </summary>
        public static string CONDITION_STATE_4 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper.
        /// </summary>
        public static string CONDITION_STATE_5 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble.
        /// </summary>
        public static string CONDITION_STATE_6 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string CONDITION_STATE_N1 {
            get {
                return ResourceManager.GetString("CONDITION_STATE_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string FAULT_CODE_0 {
            get {
                return ResourceManager.GetString("FAULT_CODE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Enumeration Value Key.
        /// </summary>
        public static string FAULT_CODE_1 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Key.
        /// </summary>
        public static string FAULT_CODE_10 {
            get {
                return ResourceManager.GetString("FAULT_CODE_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Enumeration Value Key.
        /// </summary>
        public static string FAULT_CODE_1001 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Partition.
        /// </summary>
        public static string FAULT_CODE_1002 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Session Information.
        /// </summary>
        public static string FAULT_CODE_1003 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing response Text.
        /// </summary>
        public static string FAULT_CODE_1004 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Server Name.
        /// </summary>
        public static string FAULT_CODE_1005 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Port Number.
        /// </summary>
        public static string FAULT_CODE_1006 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing User Name.
        /// </summary>
        public static string FAULT_CODE_1007 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Filter Node.
        /// </summary>
        public static string FAULT_CODE_1008 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Xml Document.
        /// </summary>
        public static string FAULT_CODE_1009 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Sort Key.
        /// </summary>
        public static string FAULT_CODE_1010 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Enumeration Value Parent Key.
        /// </summary>
        public static string FAULT_CODE_1011 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing AD Configuration.
        /// </summary>
        public static string FAULT_CODE_1012 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Enumeration Set Key.
        /// </summary>
        public static string FAULT_CODE_1013 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Alarm GUID.
        /// </summary>
        public static string FAULT_CODE_1014 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Alarm Site Name.
        /// </summary>
        public static string FAULT_CODE_1015 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Alarm Type Name.
        /// </summary>
        public static string FAULT_CODE_1016 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Item Name.
        /// </summary>
        public static string FAULT_CODE_1017 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Operator Name.
        /// </summary>
        public static string FAULT_CODE_1018 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Sort Order.
        /// </summary>
        public static string FAULT_CODE_1019 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Parameter Node.
        /// </summary>
        public static string FAULT_CODE_1020 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Condition Sequence Number.
        /// </summary>
        public static string FAULT_CODE_1021 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Command.
        /// </summary>
        public static string FAULT_CODE_1022 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Preference Type.
        /// </summary>
        public static string FAULT_CODE_1023 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Application Preference Document.
        /// </summary>
        public static string FAULT_CODE_1024 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Application Key.
        /// </summary>
        public static string FAULT_CODE_1029 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Site Name.
        /// </summary>
        public static string FAULT_CODE_1047 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Alarm State.
        /// </summary>
        public static string FAULT_CODE_1048 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Alarm GUID or Alarm State.
        /// </summary>
        public static string FAULT_CODE_1049 {
            get {
                return ResourceManager.GetString("FAULT_CODE_1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Enumeration Value Parent Key.
        /// </summary>
        public static string FAULT_CODE_11 {
            get {
                return ResourceManager.GetString("FAULT_CODE_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AD Configuration.
        /// </summary>
        public static string FAULT_CODE_12 {
            get {
                return ResourceManager.GetString("FAULT_CODE_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Enumeration Set Key.
        /// </summary>
        public static string FAULT_CODE_13 {
            get {
                return ResourceManager.GetString("FAULT_CODE_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alarm GUID .
        /// </summary>
        public static string FAULT_CODE_14 {
            get {
                return ResourceManager.GetString("FAULT_CODE_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alarm Site Name.
        /// </summary>
        public static string FAULT_CODE_15 {
            get {
                return ResourceManager.GetString("FAULT_CODE_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alarm Type Name.
        /// </summary>
        public static string FAULT_CODE_16 {
            get {
                return ResourceManager.GetString("FAULT_CODE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Item Name.
        /// </summary>
        public static string FAULT_CODE_17 {
            get {
                return ResourceManager.GetString("FAULT_CODE_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operator name.
        /// </summary>
        public static string FAULT_CODE_18 {
            get {
                return ResourceManager.GetString("FAULT_CODE_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Order.
        /// </summary>
        public static string FAULT_CODE_19 {
            get {
                return ResourceManager.GetString("FAULT_CODE_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Partition.
        /// </summary>
        public static string FAULT_CODE_2 {
            get {
                return ResourceManager.GetString("FAULT_CODE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter Node.
        /// </summary>
        public static string FAULT_CODE_20 {
            get {
                return ResourceManager.GetString("FAULT_CODE_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Response Text.
        /// </summary>
        public static string FAULT_CODE_2004 {
            get {
                return ResourceManager.GetString("FAULT_CODE_2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Condition Sequence Number.
        /// </summary>
        public static string FAULT_CODE_2021 {
            get {
                return ResourceManager.GetString("FAULT_CODE_2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Condition Sequence Number.
        /// </summary>
        public static string FAULT_CODE_21 {
            get {
                return ResourceManager.GetString("FAULT_CODE_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        public static string FAULT_CODE_22 {
            get {
                return ResourceManager.GetString("FAULT_CODE_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Preference Type.
        /// </summary>
        public static string FAULT_CODE_23 {
            get {
                return ResourceManager.GetString("FAULT_CODE_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application Preference Document.
        /// </summary>
        public static string FAULT_CODE_24 {
            get {
                return ResourceManager.GetString("FAULT_CODE_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        public static string FAULT_CODE_25 {
            get {
                return ResourceManager.GetString("FAULT_CODE_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string FAULT_CODE_26 {
            get {
                return ResourceManager.GetString("FAULT_CODE_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Function Name.
        /// </summary>
        public static string FAULT_CODE_27 {
            get {
                return ResourceManager.GetString("FAULT_CODE_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Host Address.
        /// </summary>
        public static string FAULT_CODE_28 {
            get {
                return ResourceManager.GetString("FAULT_CODE_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application Key.
        /// </summary>
        public static string FAULT_CODE_29 {
            get {
                return ResourceManager.GetString("FAULT_CODE_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Session Information.
        /// </summary>
        public static string FAULT_CODE_3 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Computer Name.
        /// </summary>
        public static string FAULT_CODE_30 {
            get {
                return ResourceManager.GetString("FAULT_CODE_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Function.
        /// </summary>
        public static string FAULT_CODE_3000 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string FAULT_CODE_3001 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP IP Connection Error.
        /// </summary>
        public static string FAULT_CODE_3002 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP IP Sending Error.
        /// </summary>
        public static string FAULT_CODE_3003 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP IP Receiving Error.
        /// </summary>
        public static string FAULT_CODE_3004 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP IP Connecting Error.
        /// </summary>
        public static string FAULT_CODE_3005 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Login.
        /// </summary>
        public static string FAULT_CODE_3006 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Authenticate.
        /// </summary>
        public static string FAULT_CODE_3007 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Issue Command.
        /// </summary>
        public static string FAULT_CODE_3008 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Impersonate New User.
        /// </summary>
        public static string FAULT_CODE_3009 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Process Multi-Entry Request.
        /// </summary>
        public static string FAULT_CODE_3010 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Operation.
        /// </summary>
        public static string FAULT_CODE_3011 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration Value Not Found.
        /// </summary>
        public static string FAULT_CODE_3012 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Name Not Found.
        /// </summary>
        public static string FAULT_CODE_3013 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Value Not Found.
        /// </summary>
        public static string FAULT_CODE_3014 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Implemented.
        /// </summary>
        public static string FAULT_CODE_3015 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Xml Node.
        /// </summary>
        public static string FAULT_CODE_3016 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out, SQL Transaction Timeout.
        /// </summary>
        public static string FAULT_CODE_3017 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked Out.
        /// </summary>
        public static string FAULT_CODE_3018 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string FAULT_CODE_3019 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Interface Type.
        /// </summary>
        public static string FAULT_CODE_31 {
            get {
                return ResourceManager.GetString("FAULT_CODE_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Partition Name and Key Count.
        /// </summary>
        public static string FAULT_CODE_3100 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Permission Resource and Level Count.
        /// </summary>
        public static string FAULT_CODE_3101 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Number.
        /// </summary>
        public static string FAULT_CODE_32 {
            get {
                return ResourceManager.GetString("FAULT_CODE_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string FAULT_CODE_3200 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string FAULT_CODE_3201 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string FAULT_CODE_3202 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Server Is Downed.
        /// </summary>
        public static string FAULT_CODE_3203 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Station Logged In.
        /// </summary>
        public static string FAULT_CODE_3204 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Badging Station Logged In.
        /// </summary>
        public static string FAULT_CODE_3205 {
            get {
                return ResourceManager.GetString("FAULT_CODE_3205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Records Per Page.
        /// </summary>
        public static string FAULT_CODE_33 {
            get {
                return ResourceManager.GetString("FAULT_CODE_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Record Count.
        /// </summary>
        public static string FAULT_CODE_34 {
            get {
                return ResourceManager.GetString("FAULT_CODE_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alarm Response Text.
        /// </summary>
        public static string FAULT_CODE_35 {
            get {
                return ResourceManager.GetString("FAULT_CODE_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password Mode.
        /// </summary>
        public static string FAULT_CODE_36 {
            get {
                return ResourceManager.GetString("FAULT_CODE_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Parameters.
        /// </summary>
        public static string FAULT_CODE_37 {
            get {
                return ResourceManager.GetString("FAULT_CODE_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Privilege Level.
        /// </summary>
        public static string FAULT_CODE_38 {
            get {
                return ResourceManager.GetString("FAULT_CODE_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Xml String.
        /// </summary>
        public static string FAULT_CODE_39 {
            get {
                return ResourceManager.GetString("FAULT_CODE_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Response Text.
        /// </summary>
        public static string FAULT_CODE_4 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Return Type.
        /// </summary>
        public static string FAULT_CODE_40 {
            get {
                return ResourceManager.GetString("FAULT_CODE_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Below Minimum.
        /// </summary>
        public static string FAULT_CODE_4000 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Above Maximum.
        /// </summary>
        public static string FAULT_CODE_4001 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Too Short.
        /// </summary>
        public static string FAULT_CODE_4002 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Too Long.
        /// </summary>
        public static string FAULT_CODE_4003 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Invalid Type.
        /// </summary>
        public static string FAULT_CODE_4004 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Null.
        /// </summary>
        public static string FAULT_CODE_4005 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Parameter Value Out Of Range.
        /// </summary>
        public static string FAULT_CODE_4006 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Key Name.
        /// </summary>
        public static string FAULT_CODE_41 {
            get {
                return ResourceManager.GetString("FAULT_CODE_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Current Alarm State.
        /// </summary>
        public static string FAULT_CODE_4100 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating Alarm.
        /// </summary>
        public static string FAULT_CODE_4101 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Not Allowed To Update To Request State.
        /// </summary>
        public static string FAULT_CODE_4102 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Has Already Completed.
        /// </summary>
        public static string FAULT_CODE_4103 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Delete Alarm.
        /// </summary>
        public static string FAULT_CODE_4104 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched Alarm Condition Sequence Number.
        /// </summary>
        public static string FAULT_CODE_4106 {
            get {
                return ResourceManager.GetString("FAULT_CODE_4106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Key Sequence Number.
        /// </summary>
        public static string FAULT_CODE_42 {
            get {
                return ResourceManager.GetString("FAULT_CODE_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Order.
        /// </summary>
        public static string FAULT_CODE_43 {
            get {
                return ResourceManager.GetString("FAULT_CODE_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string FAULT_CODE_44 {
            get {
                return ResourceManager.GetString("FAULT_CODE_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID.
        /// </summary>
        public static string FAULT_CODE_45 {
            get {
                return ResourceManager.GetString("FAULT_CODE_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Registration.
        /// </summary>
        public static string FAULT_CODE_46 {
            get {
                return ResourceManager.GetString("FAULT_CODE_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Alarm State.
        /// </summary>
        public static string FAULT_CODE_48 {
            get {
                return ResourceManager.GetString("FAULT_CODE_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Principal.
        /// </summary>
        public static string FAULT_CODE_49 {
            get {
                return ResourceManager.GetString("FAULT_CODE_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Server Name.
        /// </summary>
        public static string FAULT_CODE_5 {
            get {
                return ResourceManager.GetString("FAULT_CODE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port Number.
        /// </summary>
        public static string FAULT_CODE_6 {
            get {
                return ResourceManager.GetString("FAULT_CODE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        public static string FAULT_CODE_7 {
            get {
                return ResourceManager.GetString("FAULT_CODE_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Filter Node.
        /// </summary>
        public static string FAULT_CODE_8 {
            get {
                return ResourceManager.GetString("FAULT_CODE_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Xml Document.
        /// </summary>
        public static string FAULT_CODE_9 {
            get {
                return ResourceManager.GetString("FAULT_CODE_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string FAULT_CODE_N1 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal not found in database.
        /// </summary>
        public static string FAULT_CODE_N10 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Group not found in database.
        /// </summary>
        public static string FAULT_CODE_N11 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone not found in database.
        /// </summary>
        public static string FAULT_CODE_N12 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone is in use.
        /// </summary>
        public static string FAULT_CODE_N13 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm not found in database.
        /// </summary>
        public static string FAULT_CODE_N14 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm is in incorrect state.
        /// </summary>
        public static string FAULT_CODE_N15 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found in database.
        /// </summary>
        public static string FAULT_CODE_N16 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled action not found in database.
        /// </summary>
        public static string FAULT_CODE_N17 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge not found in database.
        /// </summary>
        public static string FAULT_CODE_N18 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder not found in database.
        /// </summary>
        public static string FAULT_CODE_N19 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening database.
        /// </summary>
        public static string FAULT_CODE_N2 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UDF type.
        /// </summary>
        public static string FAULT_CODE_N20 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter not found in database.
        /// </summary>
        public static string FAULT_CODE_N21 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading data to controller.
        /// </summary>
        public static string FAULT_CODE_N22 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal is not a reader.
        /// </summary>
        public static string FAULT_CODE_N23 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal is disabled.
        /// </summary>
        public static string FAULT_CODE_N24 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not found in database.
        /// </summary>
        public static string FAULT_CODE_N25 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output not found in database.
        /// </summary>
        public static string FAULT_CODE_N26 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel not found in database.
        /// </summary>
        public static string FAULT_CODE_N27 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Group not found in database.
        /// </summary>
        public static string FAULT_CODE_N28 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security level.
        /// </summary>
        public static string FAULT_CODE_N29 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading from or writing to database.
        /// </summary>
        public static string FAULT_CODE_N3 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm already exists.
        /// </summary>
        public static string FAULT_CODE_N30 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UDF selection choice.
        /// </summary>
        public static string FAULT_CODE_N31 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDF not found in database.
        /// </summary>
        public static string FAULT_CODE_N32 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported.
        /// </summary>
        public static string FAULT_CODE_N33 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string FAULT_CODE_N4 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error during processing.
        /// </summary>
        public static string FAULT_CODE_N5 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string FAULT_CODE_N6 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name.
        /// </summary>
        public static string FAULT_CODE_N7 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition not found in database.
        /// </summary>
        public static string FAULT_CODE_N8 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Group not found in database.
        /// </summary>
        public static string FAULT_CODE_N9 {
            get {
                return ResourceManager.GetString("FAULT_CODE_N9", resourceCulture);
            }
        }
    }
}
