// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "Logoff", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "Logon", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "AirCrew", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Ack", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Adminstrate", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Adx", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Annunciator", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Demuster", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Ful", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Inputto", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Intr", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Intrusionzone", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Lockou", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Mifare", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Mirron", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Misconfigured", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Nobypass", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Param", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Passback", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Priv", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Resync", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Timezone", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Uncalibrate", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.Converter.#GetFaultCode(JohnsonControls.BuildingSecurity.ServiceResponse.ServiceResponseCode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.Converter.#GetServiceResponseCode(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "username", Scope = "resource", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.P2000Enum.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.Converter.#GetFaultCode(JohnsonControls.BuildingSecurity.ServiceResponseCode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "p", Scope = "member", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.BuildingSecurityClient.#.ctor(JohnsonControls.BuildingSecurity.XmlRpc3.Services.IP2KService,JohnsonControls.BuildingSecurity.XmlRpc3.Services.IPartitionService,System.Web.Mvc.IDependencyResolver)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.BuildingSecurityClient.#RetrieveActiveAlarms(System.String,System.String,System.TimeZoneInfo,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "JohnsonControls.BuildingSecurity.XmlRpc3.Client.BuildingSecurityClient")]
